// Demo data for Trial Transport platform
import { Shipment, Driver, Notification, Analytics } from './types';

export const demoDrivers: Driver[] = [
  {
    id: 'drv-001',
    name: 'Michael Chen',
    email: 'michael.chen@trialtransport.com',
    phone: '+1 (555) 987-6543',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    rating: 4.9,
    totalDeliveries: 342,
    certifications: ['IATA Certified', 'Hazmat Handling', 'Temperature Control', 'DOT Certified'],
    vehicleInfo: {
      type: 'Refrigerated Van',
      licensePlate: 'ABC-1234',
      capacity: '500 lbs',
      temperatureControlled: true,
    },
    currentLocation: { lat: 40.7580, lng: -73.9855 },
    availability: 'available',
    status: 'active',
    earnings: {
      today: 285.50,
      week: 1420.75,
      month: 5680.25,
      total: 45230.80,
    },
  },
  {
    id: 'drv-002',
    name: 'Sarah Martinez',
    email: 'sarah.martinez@trialtransport.com',
    phone: '+1 (555) 234-5678',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    rating: 4.8,
    totalDeliveries: 289,
    certifications: ['IATA Certified', 'Temperature Control', 'Biohazard Certified'],
    vehicleInfo: {
      type: 'Insulated Cargo Van',
      licensePlate: 'XYZ-5678',
      capacity: '400 lbs',
      temperatureControlled: true,
    },
    currentLocation: { lat: 40.7489, lng: -73.9680 },
    availability: 'busy',
    status: 'active',
    earnings: {
      today: 195.00,
      week: 1150.50,
      month: 4890.00,
      total: 38450.25,
    },
  },
  {
    id: 'drv-003',
    name: 'James Wilson',
    email: 'james.wilson@trialtransport.com',
    phone: '+1 (555) 345-6789',
    photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    rating: 4.7,
    totalDeliveries: 256,
    certifications: ['DOT Certified', 'Temperature Control', 'Hazmat Handling'],
    vehicleInfo: {
      type: 'Standard Van',
      licensePlate: 'DEF-9012',
      capacity: '350 lbs',
      temperatureControlled: false,
    },
    currentLocation: { lat: 40.7282, lng: -73.9942 },
    availability: 'available',
    status: 'active',
    earnings: {
      today: 165.00,
      week: 980.00,
      month: 4120.50,
      total: 32890.75,
    },
  },
];

export const demoShipments: Shipment[] = [
  {
    id: 'shp-001',
    shipperId: '1',
    shipperName: 'Dr. Sarah Johnson',
    shipperCompany: 'BioTech Research Labs',
    driverId: 'drv-001',
    driverName: 'Michael Chen',
    status: 'in_transit',
    priority: 'urgent',
    pickup: {
      address: '123 Research Blvd, New York, NY 10001',
      lat: 40.7505,
      lng: -73.9934,
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      contactName: 'Lab Manager',
      contactPhone: '+1 (555) 111-2222',
    },
    dropoff: {
      address: '456 Medical Center Dr, Brooklyn, NY 11201',
      lat: 40.6942,
      lng: -73.9866,
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11201',
      contactName: 'Dr. Emily Roberts',
      contactPhone: '+1 (555) 333-4444',
    },
    specimens: [
      {
        type: 'blood',
        quantity: 24,
        unit: 'vials',
        temperatureRequirement: 'refrigerated',
        minTemp: 2,
        maxTemp: 8,
        studyProtocol: 'PROTO-2025-001',
        specialHandling: ['Fragile', 'Time-sensitive'],
      },
    ],
    scheduledPickupTime: new Date(Date.now() - 30 * 60000).toISOString(),
    estimatedDeliveryTime: new Date(Date.now() + 15 * 60000).toISOString(),
    actualPickupTime: new Date(Date.now() - 25 * 60000).toISOString(),
    trackingNumber: 'TT-2025-001234',
    chainOfCustody: [
      {
        timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
        action: 'created',
        userId: '1',
        userName: 'Dr. Sarah Johnson',
        notes: 'Shipment created for urgent delivery',
      },
      {
        timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
        action: 'picked_up',
        userId: 'drv-001',
        userName: 'Michael Chen',
        location: { lat: 40.7505, lng: -73.9934 },
        temperature: 4.5,
        signature: 'M.Chen',
      },
    ],
    documents: [],
    photos: [],
    estimatedCost: 85.00,
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'shp-002',
    shipperId: '1',
    shipperName: 'Dr. Sarah Johnson',
    shipperCompany: 'BioTech Research Labs',
    status: 'pending',
    priority: 'standard',
    pickup: {
      address: '789 Science Park, Manhattan, NY 10013',
      lat: 40.7199,
      lng: -74.0052,
      city: 'Manhattan',
      state: 'NY',
      zipCode: '10013',
      contactName: 'Research Coordinator',
      contactPhone: '+1 (555) 555-6666',
    },
    dropoff: {
      address: '321 Hospital Way, Queens, NY 11375',
      lat: 40.7282,
      lng: -73.8148,
      city: 'Queens',
      state: 'NY',
      zipCode: '11375',
      contactName: 'Lab Director',
      contactPhone: '+1 (555) 777-8888',
    },
    specimens: [
      {
        type: 'tissue',
        quantity: 12,
        unit: 'samples',
        temperatureRequirement: 'frozen',
        minTemp: -20,
        maxTemp: -15,
        studyProtocol: 'PROTO-2025-002',
        specialHandling: ['Biohazard Level 2', 'Fragile'],
      },
    ],
    scheduledPickupTime: new Date(Date.now() + 120 * 60000).toISOString(),
    trackingNumber: 'TT-2025-001235',
    chainOfCustody: [
      {
        timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
        action: 'created',
        userId: '1',
        userName: 'Dr. Sarah Johnson',
        notes: 'Standard delivery scheduled',
      },
    ],
    documents: [],
    photos: [],
    estimatedCost: 95.00,
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'shp-003',
    shipperId: '1',
    shipperName: 'Dr. Sarah Johnson',
    shipperCompany: 'BioTech Research Labs',
    driverId: 'drv-002',
    driverName: 'Sarah Martinez',
    status: 'delivered',
    priority: 'critical',
    pickup: {
      address: '555 Clinical Ave, Bronx, NY 10451',
      lat: 40.8209,
      lng: -73.9249,
      city: 'Bronx',
      state: 'NY',
      zipCode: '10451',
      contactName: 'Site Manager',
      contactPhone: '+1 (555) 999-0000',
    },
    dropoff: {
      address: '888 Research Plaza, Staten Island, NY 10301',
      lat: 40.6437,
      lng: -74.0832,
      city: 'Staten Island',
      state: 'NY',
      zipCode: '10301',
      contactName: 'Principal Investigator',
      contactPhone: '+1 (555) 111-3333',
    },
    specimens: [
      {
        type: 'blood',
        quantity: 48,
        unit: 'vials',
        temperatureRequirement: 'cryogenic',
        minTemp: -196,
        maxTemp: -150,
        studyProtocol: 'PROTO-2025-003',
        specialHandling: ['Cryogenic', 'Critical Time Window', 'Biohazard Level 3'],
      },
    ],
    scheduledPickupTime: new Date(Date.now() - 180 * 60000).toISOString(),
    estimatedDeliveryTime: new Date(Date.now() - 90 * 60000).toISOString(),
    actualPickupTime: new Date(Date.now() - 175 * 60000).toISOString(),
    actualDeliveryTime: new Date(Date.now() - 85 * 60000).toISOString(),
    trackingNumber: 'TT-2025-001233',
    chainOfCustody: [
      {
        timestamp: new Date(Date.now() - 200 * 60000).toISOString(),
        action: 'created',
        userId: '1',
        userName: 'Dr. Sarah Johnson',
        notes: 'Critical delivery - cryogenic specimens',
      },
      {
        timestamp: new Date(Date.now() - 175 * 60000).toISOString(),
        action: 'picked_up',
        userId: 'drv-002',
        userName: 'Sarah Martinez',
        location: { lat: 40.8209, lng: -73.9249 },
        temperature: -180,
        signature: 'S.Martinez',
      },
      {
        timestamp: new Date(Date.now() - 85 * 60000).toISOString(),
        action: 'delivered',
        userId: 'drv-002',
        userName: 'Sarah Martinez',
        location: { lat: 40.6437, lng: -74.0832 },
        temperature: -185,
        signature: 'PI.Signature',
      },
    ],
    documents: [],
    photos: [],
    estimatedCost: 150.00,
    actualCost: 150.00,
    createdAt: new Date(Date.now() - 200 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 85 * 60000).toISOString(),
  },
];

export const demoNotifications: Notification[] = [
  {
    id: 'notif-001',
    userId: '1',
    type: 'shipment_update',
    title: 'Shipment In Transit',
    message: 'Your shipment TT-2025-001234 is now in transit. Estimated delivery in 15 minutes.',
    read: false,
    actionUrl: '/shipper/shipments/shp-001',
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'notif-002',
    userId: '1',
    type: 'shipment_update',
    title: 'Delivery Completed',
    message: 'Shipment TT-2025-001233 has been successfully delivered.',
    read: false,
    actionUrl: '/shipper/shipments/shp-003',
    createdAt: new Date(Date.now() - 85 * 60000).toISOString(),
  },
  {
    id: 'notif-003',
    userId: '2',
    type: 'delivery_request',
    title: 'New Delivery Request',
    message: 'A new delivery request is available. Match score: 95%',
    read: false,
    actionUrl: '/driver/available',
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
];

export const demoAnalytics: Analytics = {
  totalShipments: 1247,
  activeShipments: 23,
  completedShipments: 1198,
  averageDeliveryTime: 42,
  onTimeDeliveryRate: 96.8,
  temperatureComplianceRate: 99.2,
  customerSatisfaction: 4.8,
  revenueThisMonth: 125680.50,
  topDrivers: [
    { id: 'drv-001', name: 'Michael Chen', deliveries: 342 },
    { id: 'drv-002', name: 'Sarah Martinez', deliveries: 289 },
    { id: 'drv-003', name: 'James Wilson', deliveries: 256 },
  ],
  recentActivity: [
    {
      timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
      action: 'Shipment Update',
      details: 'TT-2025-001234 is in transit',
    },
    {
      timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
      action: 'Driver Assigned',
      details: 'Michael Chen assigned to TT-2025-001234',
    },
    {
      timestamp: new Date(Date.now() - 85 * 60000).toISOString(),
      action: 'Delivery Completed',
      details: 'TT-2025-001233 delivered successfully',
    },
  ],
};